server:
  port: 3000

app:
  id: 'gateway'

ws:
  options:
    cors:
      origin: '*'
    transports:
      - 'websocket'
      - 'polling'
    path: '/ws/'

socketUI:
  namespace: '/ui'

throttle:
  ttl: 60
  limit: 20

winston:
  console:
    level: 'info'

health:
  memory:
    heapMB: 1024
    rssMB: 1024

microservice:
  timeout: 10000

recaptcha:
  url: 'https://www.google.com/recaptcha/api/siteverify'
