version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: loyalty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/.docker-conf/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    ports:
      - '6379:6379'
    volumes:
      - ~/.docker-conf/redis/data:/data

  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq