from: 'Trading System <viktorr.plotnikov@gmail.com>'

throttle:
  ttl: 60
  limit: 20

app:
  name: 'Trading System'

mail:
  from: '"Trading System No-Reply" <viktorr.plotnikov@gmail.com>'

hbs:
  layouts: 'templates/emails/layouts'
  partials: 'templates/emails/partials'

winston:
  console:
    level: 'info'

health:
  memory:
    heapMB: 1024
    rssMB: 1024
  disk:
    percentThreshold: 0.8
    thresholdGB: 100
