cache:
  ttl: 60000
  prefix: 'LOYALTY_SERVICE'

throttle:
  ttl: 60
  limit: 20

winston:
  console:
    level: 'info'

health:
  memory:
    heapMB: 1024
    rssMB: 1024

microservice:
  timeout: 10000
