db:
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'loyalty'

redis:
  host: 'localhost'
  port: 6379

cache:
  ttl: 60
  prefix: 'AUTH_SERVICE'

app:
  id: 'auth'
  admin:
    email: 'viktorr.plotnikov@gmail.com'
    password: 'password'

jwt:
  secret: 'kslhfOIEFY#(*ru_s9pcjc90u2f0jc3DJO-'
  accessExpiresIn: 900
  refreshExpiresIn: '10 days'

throttle:
  ttl: 60
  limit: 20

winston:
  console:
    level: 'info'

2fa_auth:
  name: 'Dev Loyalty Program'

health:
  memory:
    heapMB: 1024
    rssMB: 1024

microservice:
  timeout: 10000

recaptcha:
  secret: '6Ld1FuMnAAAAAErhmKHLd95C4uXi1tDERj35MI3h'
  url: 'https://www.google.com/recaptcha/api/siteverify'
  score: 0.5
