db:
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'loyalty'

redis:
  host: 'localhost'
  port: 6379

mq:
  - 'amqp://localhost:5672'

winston:
  console:
    level: 'info'

microservice:
  timeout: 10000
